package:
  name: openalea.sconsx
  version: 2.0.0

source:
  git_url: https://github.com/openalea/sconsx

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - openalea.deploy
  run:
    - python
    - scons
    - openalea.deploy

test:
  imports:
    - SCons
    - openalea.sconsx

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-c License
