package:
  name: libqglviewer
  version: 2.6.4

source:
  git_url: https://github.com/GillesDebunne/libQGLViewer
  git_tag: v2.6.4
  patches:
   # List any patch files here
   - QGLViewer_pro.patch
   - examples.pri.patch
   - libQGLViewer.pro.patch


build:
  number: 0
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - qt 4.8.6

  run:
    # python dependency is here due to libboost-python library that depends on
    # python version
    - qt 4.8.6

about:
  home: http://www.libqglviewer.com
  license: GPL

