package:
  name: vplants.plantgl
  version: 2.18.0

source:
  git_url: https://github.com/VirtualPlants/plantgl
  patches:
   # List any patch files here
   - setup.patch

about:
  home: http://openalea.gforge.inria.fr
  license: GPL/LGPL
  summary: An open-source graphic toolkit for the creation, simulation and analysis of 3D virtual plants.

build:
  preserve_egg_dir: True
  number: 3

requirements:
  # it doesn't really require python, but maybe that will fix
  # the missing bin directory
  build:
   - python
   - m4
   - setuptools
   - openalea.deploy
   - scons
   - openalea.sconsx
   - qt ==4.8.6 [osx]
   - qt ==4.8.7 [linux]
   - boost [osx]
   - boost [linux]
   - bison
   - flex 2.5.39
   - cgal [osx]
   - cgal [linux]
   - gmp 6.1.1 [osx]
   - gmp  [linux]
   - ann
   - eigen 3.2.8 [osx]
   - eigen [linux]
   - qhull
   - patchelf [linux]
  run:
   - python
   - qt ==4.8.6 [osx]
   - qt ==4.8.7 [linux]
   - gmp
   - mpfr
   - cgal [osx]
   - cgal [linux]
   - qhull
   - ann
   - boost [osx]
   - boost [linux]

#test:
  # Python imports
  #imports:
  #  - openalea.plantgl

